const DeliveryStatus = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERY_ATTEMPTED: 'DELIVERY_ATTEMPTED',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETURN_INITIATED: 'RETURN_INITIATED',
  RETURNED: 'RETURNED',
});

module.exports = DeliveryStatus;
