module.exports = Object.freeze({
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  AGENT_ASSIGNED: 'AGENT_ASSIGNED',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  DOCUMENTS_REQUIRED: 'DOCUMENTS_REQUIRED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
});
