module.exports = Object.freeze({
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  AGENT_APPROVED: 'AGENT_APPROVED',
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  AGENT_ASSIGNED: 'AGENT_ASSIGNED',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  DOCUMENTS_REQUIRED: 'DOCUMENTS_REQUIRED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  ID_PROOF_VERIFIED: 'ID_PROOF_VERIFIED',
  ID_PROOF_REJECTED: 'ID_PROOF_REJECTED',
  INFO: 'INFO',
});
